server:  
    port: 9090
    servlet: 
       session.timeout: 60000   
    undertow:  
        io-threads: 16  
        worker-threads: 256  
        buffer-size: 1024  
        buffers-per-region: 1024  
        direct-buffers: true 
logging:
    level.root: info
    level.org.springframework: warn
    level.com.yc: info
    file: D:\tmp\BBS.log
swagger: 
    enabled: true